management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082
spring:
  application:
    name: Greet-Service
  boot:
    admin:
      client:
        url: http://localhost:9090/
